version: "3"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 123qweQWE
      PGDATA: /var/lib/postgresql/data/pgdata

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db